'use client';

import { LandingHeader } from '@/components/layout/LandingHeader';
import { Link } from '@/i18n/routing';

export function TermsContent() {
    return (
        <div className="space-y-10 text-sm leading-relaxed text-foreground/80">

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">1. Acceptance of Terms</h2>
                <p className="text-muted-foreground">
                    By registering for or using WageX, you represent that you are at least 18 years of age, have the legal
                    authority to enter into these Terms on behalf of yourself or your organisation, and agree to comply with
                    all applicable laws and regulations.
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">2. Description of Service</h2>
                <p className="text-muted-foreground">
                    WageX is a payroll and workforce management software platform. It is provided as a tool to assist
                    businesses in managing employee records, payroll calculations, attendance, leave, and statutory
                    document generation. WageX is a <strong className="text-foreground">software tool only</strong> and
                    does not constitute legal, financial, accounting, or HR advisory services of any kind.
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">3. User Responsibilities</h2>
                <p>You are solely responsible for:</p>
                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                    <li>The accuracy and completeness of all data you enter into the platform</li>
                    <li>Verifying all payroll calculations, EPF/ETF figures, and statutory submissions before use</li>
                    <li>Ensuring your use of the platform complies with all applicable Sri Lankan labour, tax, and statutory laws</li>
                    <li>Maintaining the confidentiality and security of your account credentials</li>
                    <li>All actions taken by any user accessing the platform under your account</li>
                    <li>Obtaining any necessary consents from your employees for data processing</li>
                </ul>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">4. No Warranty — As-Is Service</h2>
                <p className="text-muted-foreground">
                    THE SERVICE IS PROVIDED <strong className="text-foreground">&quot;AS IS&quot;</strong> AND
                    <strong className="text-foreground"> &quot;AS AVAILABLE&quot;</strong> WITHOUT ANY WARRANTY OF ANY KIND,
                    EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, WAGEX EXPRESSLY DISCLAIMS ALL WARRANTIES,
                    INCLUDING BUT NOT LIMITED TO:
                </p>
                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                    <li>Warranties of merchantability or fitness for a particular purpose</li>
                    <li>Accuracy, completeness, or reliability of any calculation, report, or document generated by the platform</li>
                    <li>Uninterrupted or error-free operation of the service</li>
                    <li>That the platform meets your specific legal or regulatory compliance requirements</li>
                </ul>
                <p className="text-muted-foreground">
                    WageX does not guarantee that EPF, ETF, or any other statutory calculations produced by the platform
                    are accurate or compliant. <strong className="text-foreground">You must independently verify all
                    statutory submissions with a qualified professional before filing.</strong>
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">5. Limitation of Liability</h2>
                <p className="text-muted-foreground">
                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WAGEX, ITS OPERATORS, DEVELOPERS, EMPLOYEES,
                    AND AFFILIATES SHALL NOT BE LIABLE FOR ANY:
                </p>
                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                    <li>Direct, indirect, incidental, consequential, or punitive damages</li>
                    <li>Loss of revenue, profits, data, or business opportunities</li>
                    <li>Errors or inaccuracies in payroll, statutory, or compliance calculations</li>
                    <li>Penalties, fines, or legal consequences arising from incorrect or late statutory submissions</li>
                    <li>Damages resulting from unauthorised access to your account or data</li>
                    <li>Service interruptions, downtime, or data loss</li>
                </ul>
                <p className="text-muted-foreground">
                    This limitation applies regardless of whether WageX has been advised of the possibility of such damages
                    and regardless of the legal theory under which damages are sought.
                    <strong className="text-foreground"> Your sole remedy for dissatisfaction with the Service is to
                    discontinue use of the Service.</strong>
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">6. Indemnification</h2>
                <p className="text-muted-foreground">
                    You agree to indemnify, defend, and hold harmless WageX and its operators, developers, and affiliates
                    from and against any claims, liabilities, damages, losses, costs, or expenses (including reasonable
                    legal fees) arising out of or in connection with:
                </p>
                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                    <li>Your use or misuse of the Service</li>
                    <li>Your violation of these Terms</li>
                    <li>Any inaccurate data you input into the platform</li>
                    <li>Your failure to verify calculations or comply with applicable laws</li>
                    <li>Any claim by a third party (including your employees) arising from your use of WageX</li>
                </ul>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">7. Statutory Compliance Disclaimer</h2>
                <p className="text-muted-foreground">
                    WageX generates EPF and ETF forms, payslips, and other statutory documents as a convenience. These
                    documents are generated based solely on the data you provide. <strong className="text-foreground">WageX
                    makes no representation that such documents are legally compliant, accurate, or sufficient for
                    submission to any government authority.</strong> You remain solely responsible for the accuracy of
                    all filings and for compliance with the Employees&apos; Provident Fund Act, the Employees&apos; Trust
                    Fund Act, the Shop and Office Employees Act, and all other applicable Sri Lankan legislation.
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">8. Intellectual Property</h2>
                <p className="text-muted-foreground">
                    All software, design, code, branding, and content comprising the WageX platform is the intellectual
                    property of WageX and its operators. You may not copy, reproduce, distribute, reverse engineer, or
                    create derivative works from any part of the platform without prior written consent.
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">9. Termination</h2>
                <p className="text-muted-foreground">
                    We reserve the right to suspend or terminate your access to WageX at any time, with or without notice,
                    for any reason including breach of these Terms. Upon termination, your right to use the Service ceases
                    immediately. Provisions of these Terms that by their nature should survive termination shall survive,
                    including limitations of liability and indemnification.
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">10. Governing Law</h2>
                <p className="text-muted-foreground">
                    These Terms shall be governed by and construed in accordance with the laws of Sri Lanka. Any disputes
                    arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the
                    courts of Sri Lanka.
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">11. Changes to Terms</h2>
                <p className="text-muted-foreground">
                    We may modify these Terms at any time. Changes will be posted on this page with an updated
                    &quot;Last updated&quot; date. Your continued use of WageX after changes are posted constitutes
                    acceptance of the revised Terms. It is your responsibility to review these Terms periodically.
                </p>
            </section>

            <section className="space-y-3">
                <h2 className="text-lg font-black text-foreground uppercase tracking-tight">12. Contact</h2>
                <p className="text-muted-foreground">
                    For any questions regarding these Terms, contact us at:<br />
                    <a href="mailto:anushangasharada@gmail.com" className="underline hover:text-foreground">anushangasharada@gmail.com</a><br />
                    <a href="tel:+94717539478" className="underline hover:text-foreground">+94 71 753 9478</a>
                </p>
            </section>

        </div>
    );
}

export default function TermsPage() {
    const lastUpdated = 'April 24, 2026';

    return (
        <div className="min-h-screen bg-background">
            <LandingHeader />

            <main className="container mx-auto max-w-3xl px-6 py-16 md:py-24">
                <div className="space-y-3 mb-12">
                    <p className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Last updated: {lastUpdated}</p>
                    <h1 className="text-4xl md:text-5xl font-black tracking-tight italic">Terms of Service</h1>
                    <p className="text-muted-foreground text-base leading-relaxed">
                        These Terms of Service (&quot;Terms&quot;) govern your access to and use of the WageX LK platform
                        (&quot;WageX&quot;, &quot;the Service&quot;). By accessing or using WageX, you agree to be bound by
                        these Terms in full. If you do not agree, do not use the Service.
                    </p>
                </div>

                <TermsContent />

                <div className="mt-16 pt-8 border-t border-neutral-200 dark:border-neutral-800">
                    <Link href="/" className="text-xs font-bold text-muted-foreground hover:text-foreground uppercase tracking-widest transition-colors">
                        ← Back to Home
                    </Link>
                </div>
            </main>
        </div>
    );
}
